version: '2'

services:
  db:
    build: .
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=meterstanden_test
      - TZ=Europe/Amsterdam
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
